# Site settings
title: Jota on Code
email: garcia_juan_j@yahoo.com.ar
description: > # this means to ignore newlines until "baseurl:"
    Thanks for visiting, I am an Information Systems Engineer that loves to learn new technologies, open minded, gratefull and humble I would like to help making internet a better place.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jotaoncode.com/" # the base hostname & protocol for your site
twitter: "https://twitter.com/Juancho_1985_"
linkedin: "https://ar.linkedin.com/in/garciajuanjose"
stackoverflow: "https://careers.stackoverflow.com/juangarcia"
github:  "https://github.com/jotaoncode"
thingiverse: "https://www.thingiverse.com/Jota_1985/designs"
youtubechannel: "https://www.youtube.com/channel/UC3w8F2SQIkBg2UrwUkhx7pw"
production: false

# Permalinks
permalink: /blog/:categories/:year/:month/:day/:title/

sass:
  style: compressed

#gem:
#  - octopress-debugger

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
