# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jota On Code
email: garcia_juan_j@yahoo.com.ar
description: > # this means to ignore newlines until "baseurl:"
    Thanks for visiting, I am an Information Systems Engineer that loves to learn new technologies, open minded, gratefull and humble I would like to help making internet a better place.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jotaoncode.com" # the base hostname & protocol for your site
twitter: "https://twitter.com/Juancho_1985_"
linkedin: "https://ar.linkedin.com/in/garciajuanjose"
stackoverflow: "http://careers.stackoverflow.com/juangarcia"
github:  "https://github.com/jotaoncode"

# Permalinks
permalink: /blog/:categories/:year/:month/:day/:title/

#gem:
#  - octopress-debugger

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
